### ISSUE TITLE
Rotation Issue and mirrored screen.

### ISSUE THREAD

**Issue by SathvikKS** [tpkarras/Mirror2RearUltra#1]
I have noticed that when you rotate the phone from portrait to landscape and then back to portrait, only half the screen on the back would be covered. Also I noticed that the image displayed is a mirrored image of the screen(like if you see the phone screen through the mirror)

**Comment by tpkarras** [comment]
which version are you using? cause 1.0.2 has fixes for that.

also the screen is mirrored for compatibility with camera apps. 1.0-final should have the screen unmirrored.

**Comment by SathvikKS** [comment]
I downloaded the latest version from the release. It's 1.0.2

**Comment by PerezChilli** [comment]
I confirm. MIUI 13.0.3.0.SKAIDXM - screen is mirrored.

**Comment by ProInGramming** [comment]
Miui 14 same problem. Also the screen goes blank every 15 minutes and I need to double tap on it.

**Comment by tpkarras** [comment]
fixed all issues. mirroring i won't fix cause it's intended behavior. i don't know if anybody's going to play YouTube videos using the rear screen.
