### ISSUE TITLE
Support for MIUI 14

### ISSUE THREAD

**Issue by MatheusBoettger7** [tpkarras/Mirror2RearUltra#3]
Hello friend.  I use your apk since forever.  It worked perfectly all this time.  But in MIUI 14 it is no longer centered, it shows the second screen too far to the left.  I would love to be able to continue using your apk

**Comment by MatheusBoettger7** [comment]
.

**Comment by pjgoncalves72** [comment]
Hello, 
this app is awesome but since Miui14 the screen is not centered.
Please bring this app to life on Miui14 🙂
Thank you

**Comment by tpkarras** [comment]
hey all.

I hear you. I've been trying to figure out how to bring it to life on Android 13 but I keep hitting a roadblock. All takes time though, I thought it was simply adjusting some variables but I guess Android 13 changed the display driver to work differently.

**Comment by tpkarras** [comment]
okay, uploaded new version. tell me if there's any bugs on any android versions.

**Comment by pjgoncalves72** [comment]
> okay, uploaded new version. tell me if there's any bugs on any android versions.

Working on Miui14, thank you!

**Comment by pjgoncalves72** [comment]
Hey!

Noticed that the screen turns off after some seconds, need to double tap to activate rear screen again.

On the previous version it was always on while quick tile was active.

Is it possible to keep always on while quick tile is active?

Many thanks!

**Comment by tpkarras** [comment]
> Noticed that the screen turns off after some seconds, need to double tap to activate rear screen again.
> 
> On the previous version it was always on while quick tile was active.
> 
> Is it possible to keep always on while quick tile is active?

unfortunately the input command line program doesn't seem to be working at the moment. it may work on Android 12 but not on 13 atm. trust me I've tried.

any fix for this would be greatly appreciated

**Comment by pjgoncalves72** [comment]
Thanks for trying 👍

> > Noticed that the screen turns off after some seconds, need to double tap to activate rear screen again.
> > 
> > On the previous version it was always on while quick tile was active.
> > 
> > Is it possible to keep always on while quick tile is active?
> 
> unfortunately the input command line program doesn't seem to be working at the moment. it may work on Android 12 but not on 13 atm. trust me I've tried.
> 
> any fix for this would be greatly appreciated

**Comment by tresor** [comment]
tpkarras, tell me please what command can I run a rear screen mirror using adb shell

**Comment by tpkarras** [comment]
removed the command line and used the code from the MIUI camera app to keep the screen on. let me know if everything is alright.

**Comment by tpkarras** [comment]
everything's alright i guess.
