### ISSUE TITLE
Best app for Xiaomi 11 ultra

### ISSUE THREAD

**Issue by tanktorres7** [tpkarras/Mirror2RearUltra#7]
I'm a fan of this application irá wonderful how can i use gcam,helping to hace the top of the top pictures. The only problema that i found its the rotation of the screen. Please, Please fix this i beg it. This make my xiaomi the perfect device

**Comment by tanktorres7** [comment]
Im using the 1.0.3. The 1.0.2 works perfect on Android 12.

**Comment by tpkarras** [comment]
hey. I fixed the rotation bug in 1.0.4 as well as the screen staying on without the use of a timer script. hope it works for you.

**Comment by Shamkook** [comment]
1.0.4 does not work  1.0.3 worked, although the screen rotated. I have miui version 13

**Comment by tpkarras** [comment]
what are you experiencing? what's the message in the summary?

**Comment by Shamkook** [comment]
1.0.4 does not turn on at all

**Comment by tpkarras** [comment]
> 1.0.4 does not turn on at all
it's supposed to turn on the always on mode of the screen. to remove dependencies on the timer script.

it works on my build. turns on as expected.

**Comment by Shamkook** [comment]
menu icon disappears

**Comment by tpkarras** [comment]
> 1.0.4 does not turn on at all

working on the latest Xiaomi.EU dev build. don't know if the camera method for turning on the rear is different on global builds? there is a mode that causes the rear screen to be always on.

**Comment by Shamkook** [comment]
app icon disappears

**Comment by tpkarras** [comment]
> app icon disappears

this is a quick tile app. you need to put it in quick settings and use that to open the app.

**Comment by Shamkook** [comment]
fast tile appears

**Comment by Shamkook** [comment]
1.0.2 works for me and 1.0.3 works too

**Comment by tpkarras** [comment]
can you send a video of what is happening? don't know if it's ROM related or not

**Comment by Shamkook** [comment]
sent 2 videos

**Comment by Shamkook** [comment]
1.0.2 back screen works and 1.0.4 back screen does not turn on

**Comment by Shamkook** [comment]
great app thanks for it! 1.0.4 what changes

**Comment by Shamkook** [comment]
great app thanks for it! 1.0.4 what changes

**Comment by tpkarras** [comment]
> great app thanks for it! 1.0.4 what changes

used Xiaomi (MIUI) Camera's method for turning the screen on and off and to make it stay on.

**Comment by tpkarras** [comment]
i don't think there are any issues. otherwise i would of heard of them already. if any issues pop up, please open a new issue.

**Comment by snackasnack** [comment]
I had similar issues too, using MIUI 14.0.6.0, China ROM. After installing ver 1.0.4, app icon doesnt appear like it did for other versions. Quick tile was still available but rear display will not turn on (luminated black screen) after Mirror2RearUltra is activated. Sounds like similar issues with Shamkook.
